### ISSUE TITLE
Login and Signup pages

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-application#14]
The login and sign up pages have been redesigned with the style of Lofft, this should be updated.

### Todo
- [ ] Update back button icon 
- [ ] Change input fields to purple
- [ ] Add view password eye
- [ ] Add terms and conditions section

The addition of google and apple authentication should be completed next on their branch.

**Comment by jhibbeard89** [comment]
Closes #15
